export const CREATE_USER = 'USER/CREATE_USER';
export const EDIT_USER = 'USER/EDIT_USER';
export const SET_EDIT_USER = 'USER/SET_EDIT_USER';
export const SET_CREATE_USER = 'USER/SET_CREATE_USER';
export const DELETE_USER = 'USER/DELETE_USER';
export const SET_DELETE_USER = 'USER/SET_DELETE_USER';
export const REQUEST_USERS = 'USER/REQUEST_USERS';
export const SET_REQUEST_USERS = 'USER/SET_REQUEST_USERS';
